---
title: "Premier League Analysis"
output: html_document
date: "Last Compiled on `r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rvest)
library(stringr)
library(dplyr)
library(httr)
library(tidyr)
```

## Introduction

This project serves to learn about web scraping data using the rvest library and performing analysis on Premier League players on 2023/2024 season

```{r message=FALSE}

url <- "https://fbref.com/en/comps/9/stats/Premier-League-Stats#stats_standard"

# Use httr library to GET the url and convert the content as text
html_resp <- GET(url)
html <- content(html_resp, as = "text") %>% 
  str_remove_all("(<!--|-->)") %>% # Remove comments
  read_html() # Read the text as html

players <- html %>% 
  html_element("table#stats_standard") %>% # THE table to use
  html_table()

# Remove parent header and promote first row to header
colnames(players) <- ifelse(
  colnames(players) != "",
  paste0(players[1,], "_", colnames(players)),
  players[1,]
  )

players <- players[-1, ]

players <- players %>%
  mutate(`Min_Playing Time` = gsub(",", "", `Min_Playing Time`),
         `Min_Playing Time` = as.integer(`Min_Playing Time`),
         `PrgC_Progression` = as.integer(`PrgC_Progression`),
         `Ast_Performance` = as.integer(`Ast_Performance`)) %>%
  filter(`Player` != "Player")

colnames(players)

## Need a fast way to convert chr to num
```

### Scatterplot of xG per 90 and xAG per 90 For Players On or Over Median Playing Time Minutes

```{r warning=FALSE}

library(ggplot2)
library(ggrepel)

median_played <- players %>% 
  pull(`Min_Playing Time`) %>%
  median(na.rm = TRUE)

xGA_per90_players <- players %>%
  select(`Player`, `Min_Playing Time`, `xG_Per 90 Minutes`, `xAG_Per 90 Minutes`) %>%
  mutate(`xG_Per 90 Minutes` = as.double(`xG_Per 90 Minutes`),
         `xAG_Per 90 Minutes` = as.double(`xAG_Per 90 Minutes`)) %>%
  filter(`Min_Playing Time` >= median_played) %>%
  drop_na()

summary(xGA_per90_players)

## set color for top players of xG and xA per 90

topxG_range <- quantile(xGA_per90_players$`xG_Per 90 Minutes`, 0.95)
topxA_range <- quantile(xGA_per90_players$`xAG_Per 90 Minutes`, 0.95)

xGA_per90_players$top_player <- ifelse(xGA_per90_players$`xG_Per 90 Minutes` >= topxG_range & xGA_per90_players$`xAG_Per 90 Minutes` >= topxA_range, "Top", "Bottom")

ggplot(xGA_per90_players, aes(`xAG_Per 90 Minutes`, `xG_Per 90 Minutes`)) + 
  geom_jitter(aes(color = top_player)) +
  geom_text_repel(aes(label = ifelse(top_player == "Top", `Player`, NA)), vjust = 0.5, size = 3) +
  geom_abline(linetype = "dashed") +
  labs(caption = paste("Median Minutes:", median_played)) +
  scale_color_manual(values = c("Top" = "red", "Bottom", "gray")) +
  theme(legend.position = "none")


```

### Progressive Passes Analysis

```{r warning=FALSE}

PrgC_players <- players %>% 
  drop_na(`PrgC_Progression`) %>%
  filter(`Min_Playing Time` >= median_played)

topPrgC_range <- quantile(PrgC_players$`PrgC_Progression`, 0.95)

PrgC_players %>%
  filter(`PrgC_Progression` >= topPrgC_range) %>%
  top_n(10, `PrgC_Progression`) %>%
  ggplot(aes(reorder(`Player`, `PrgC_Progression`), `PrgC_Progression`)) +
  geom_col() +
  coord_flip()


```

### Progressive Pass and Assists

```{R}

PrgC_Ast_players <- players %>% 
  drop_na(`PrgC_Progression`, `Ast_Performance`) %>%
  filter(`Min_Playing Time` >= median_played) %>%
  select(`Player`, `PrgC_Progression`, `Ast_Performance`)

topPrgC_range <- quantile(PrgC_Ast_players$`PrgC_Progression`, 0.95)
topAst_range <- quantile(PrgC_Ast_players$`Ast_Performance`, 0.95)

PrgC_Ast_players$top_player <- ifelse(PrgC_Ast_players$`PrgC_Progression` >= topPrgC_range & PrgC_Ast_players$`Ast_Performance` >= topAst_range, "Top", "Bottom")

ggplot(PrgC_Ast_players, aes(`PrgC_Progression`, `Ast_Performance`)) + 
  geom_jitter(aes(color = top_player)) +
  geom_text_repel(aes(label = ifelse(top_player == "Top", `Player`, NA)), vjust = 0.5, size = 3) +
  geom_abline(linetype = "dashed") +
  labs(caption = paste("Median Minutes:", median_played)) +
  scale_color_manual(values = c("Top" = "red", "Bottom", "gray")) +
  theme(legend.position = "none")

```